export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS"
export const ADD_LOCATION_FAILED = "ADD_LOCATION_FAILED"
export const ADD_GATE_SUCCESS = "ADD_GATE_SUCCESS"
export const ADD_GATE_FAILED = "ADD_GATE_FAILED"